[workspace]
members = [
	"framework/unitest",
	"framework/unitest-native",
]

exclude = [
	"examples/**/*",
	"target/**/*",
	"Cargo.lock",
]

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
